before:
  hooks:
    - 'go mod tidy'
    - 'go mod verify'

builds:
  -
    id: 'local-exec-linter'
    main: ./cmd/lint-local-exec
    env:
      - 'CGO_ENABLED=0'
      - 'GO111MODULE=on'
      - 'GOPROXY=https://proxy.golang.org,direct'
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - '-trimpath'
    ldflags:
      - '-s'
      - '-w'
      - '-X=github.com/abcxyz/secure-setup-terraform/cmd/lint-local-exec/version.Name={{ .ProjectName }}'
      - '-X=github.com/abcxyz/secure-setup-terraform/cmd/lint-local-exec/version.Version={{ .Version }}'
      - '-X=github.com/abcxyz/secure-setup-terraform/cmd/lint-local-exec/version.Commit={{ .Commit }}'
      - '-extldflags=-static'
    targets:
      - 'darwin_amd64'
      - 'darwin_arm64'
      - 'linux_amd64'
      - 'linux_arm64'
      - 'windows_amd64'
      - 'windows_arm64'
    binary: '{{ .ProjectName }}'
  -
    id: 'setup-terraform-linter'
    main: ./cmd/lint-setup-terraform
    env:
      - 'CGO_ENABLED=0'
      - 'GO111MODULE=on'
      - 'GOPROXY=https://proxy.golang.org,direct'
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - '-trimpath'
    ldflags:
      - '-s'
      - '-w'
      - '-X=github.com/abcxyz/secure-setup-terraform/cmd/lint-setup-terraform/version.Name={{ .ProjectName }}'
      - '-X=github.com/abcxyz/secure-setup-terraform/cmd/lint-setup-terraform/version.Version={{ .Version }}'
      - '-X=github.com/abcxyz/secure-setup-terraform/cmd/lint-setup-terraform/version.Commit={{ .Commit }}'
      - '-extldflags=-static'
    targets:
      - 'darwin_amd64'
      - 'darwin_arm64'
      - 'linux_amd64'
      - 'linux_arm64'
      - 'windows_amd64'
      - 'windows_arm64'
    binary: '{{ .ProjectName }}'

# dockers:
#   -
#     image_templates:
#       - 'ghcr.io/bradegler/{{ .ProjectName }}:{{ .Major }}'
#       - 'ghcr.io/bradegler/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}'
#       - 'ghcr.io/bradegler/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
#       - 'ghcr.io/bradegler/{{ .ProjectName }}:latest'
#     build_flag_templates:
#       - '--pull'
#       - '--label=org.opencontainers.image.created={{ .CommitTimestamp }}'
#       - '--label=org.opencontainers.image.description=osprey is a tool for securely building open source projects and ensuring their provenance.'
#       - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
#       - '--label=org.opencontainers.image.source=https://github.com/bradegler/osprey'
#       - '--label=org.opencontainers.image.title={{ .ProjectName }}'
#       - '--label=org.opencontainers.image.version={{ .Version }}'

# archives:
#   - format: 'tar.gz'
#     name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
#     format_overrides:
#       - goos: 'windows'
#         format: 'zip'

# checksum:
#   name_template: '{{ .ProjectName }}_{{ .Version }}_SHA512SUMS'
#   algorithm: 'sha512'

# release:
#   draft: false

# changelog:
#   use: 'github-native'
