# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'secure-setup-terraform action'
description: 'Verify that the installed terraform binary matches a pre-computed hash. Ensure that there is a checked in provider lock file and that it is read only so that terraform cannot update it.'
inputs:
  terraform_version:
    description: 'The terraform version to install'
    default: '1.3.3'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'checkout'
      uses: 'actions/checkout@v3'
    - name: 'download-artifacts'
      shell: 'bash'
      env:
        RELEASE_VERSION: '0.1.0'
        RELEASE_LOCATION: 'https://github.com/abcxyz/secure-setup-terraform/releases/tag'
      run: |-
        curl -H "Authorization: token ${{ github.token }}" -O "${{env.RELEASE_LOCATION}}/v${{env.RELEASE_VERSION}}/secure-setup-terraform_${{env.RELEASE_VERSION}}_linux_amd64.tar.gz"
        curl -H "Authorization: token ${{ github.token }}" -o terraform-checksums.json "${{env.RELEASE_LOCATION}}/v${{env.RELEASE_VERSION}}/secure-setup-terraform_${{env.RELEASE_VERSION}}_checksums.json"
        tar xf secure-setup-terraform_${{env.RELEASE_VERSION}}_linux_amd64.tar.gz

    # Recursively search for terraform files in the current repo and run a linter that fails when it finds calls to 'local-exec'
    - name: 'lint-terraform'
      shell: 'bash'
      run: ./lint-terraform ./

    # Search the .github/workflows for this project and run a linter that fails if it finds a direct call to the 'hashicorp/setup-terraform' action
    - name: 'lint-action'
      shell: 'bash'
      run: ./lint-action ./.github/workflows

    - name: 'setup-terraform'
      uses: 'hashicorp/setup-terraform@v2'
      with:
        terraform_version: '${{ inputs.terraform_version }}'
    - 
      name: 'verify-binary-checksum'
      shell: 'bash'
      run: |-
        CHECKSUM=$(jq -r '.versions[] | select(.version=="1.3.3" and .arch=="amd64" and .os=="linux") | .binary_checksum' < terraform-checksums.json)
        echo "${CHECKSUM}  $(which terraform)" > terraform.sha256
        shasum --algorithm 256 --check terraform.sha256


