# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'update-checksums-file'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */1 * *'

jobs:
  update-checksums:
    permissions:
      contents: 'write'
      packages: 'write'
      pull-requests: 'write'
      id-token: 'write'

    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        id: 'checkout'
        uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' # ratchet:actions/checkout@v4

      # Generate updates to the checksum file if there are new released versions of terraform
      - name: 'Generate Updates'
        id: 'generate-updates'
        run: './.github/generate_version_checksums.sh $GITHUB_WORKSPACE/terraform-checksums.json;'

      # Generate a token that has permission to author a pull request
      - name: 'Mint Token'
        id: 'mint-token'
        if: '${{ env.CHANGES }}'
        uses: 'abcxyz/github-token-minter/.github/actions/mint-token@4e83d0b3f01f2b084dbbd3c6da07b29a2c032c6e'
        with:
          wif_provider: '${{ vars.TOKEN_MINTER_WIF_PROVIDER }}'
          wif_service_account: '${{ vars.TOKEN_MINTER_WIF_SERVICE_ACCOUNT }}'
          service_audience: '${{ vars.TOKEN_MINTER_SERVICE_AUDIENCE }}'
          service_url: '${{ vars.TOKEN_MINTER_SERVICE_URL }}'
          requested_permissions: |-
            {
              "repositories": ["secure-setup-terraform"],
              "permissions": {
                "pull_requests": "write",
                "contents": "write"
              }
            }

      # Create a pull request with updated files
      - name: 'Create/Update Pull Request'
        if: '${{ env.CHANGES }}'
        uses: 'abcxyz/pkg/.github/actions/create-pull-request@main' # ratchet:exclude
        with:
          token: '${{ steps.mint-token.outputs.token }}'
          base_branch: '${{ github.event.repository.default_branch }}'
          head_branch: '${{ env.PR_BRANCH }}' # set via mint-token step
          title: 'chore: [automated] Terraform checksum updates for ${{ env.UPDATE_DATE }}' # set via mint-token step
          body: 'Adds Terraform binary checksums for ${process.env.CHANGES} versions: ${{ env.VERSIONS }}' # set via mint-token step
          changed_paths: |-
            [
              "terraform-checksums.json",
              "VERSION"
            ]
